// ============================================================================
// TERMINALLY ONLINE — NON-RSS INTELLIGENCE SOURCES
// Public APIs, JSON feeds, WebSocket streams, government data, IoT sensors
// ============================================================================

export interface ApiSource {
  id: string;
  name: string;
  category: string;
  endpoint: string;
  method: 'GET' | 'POST' | 'WS';
  auth: 'none' | 'key' | 'oauth';
  refreshMs: number;
  description: string;
  parser?: string; // name of parser function if response needs special handling
}

// ============================================================================
// NYC / URBAN INTELLIGENCE — Midtown Foot Traffic + Urban Sensors
// ============================================================================
export const NYC_API_SOURCES: ApiSource[] = [
  {
    id: 'citibike-stations',
    name: 'Citi Bike Station Status',
    category: 'nyc',
    endpoint: 'https://gbfs.citibikenyc.com/gbfs/en/station_status.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 60_000,
    description: 'Real-time bike/dock availability at every station — proxy for neighborhood activity',
  },
  {
    id: 'citibike-station-info',
    name: 'Citi Bike Station Info',
    category: 'nyc',
    endpoint: 'https://gbfs.citibikenyc.com/gbfs/en/station_information.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Station locations, capacities, names — reference data for mapping',
  },
  {
    id: 'nyc-traffic-speed',
    name: 'NYC Real-Time Traffic Speed',
    category: 'nyc',
    endpoint: 'https://data.cityofnewyork.us/resource/i4gi-tjb9.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 120_000,
    description: 'Real-time traffic speed data from NYC DOT sensors across major arterials',
  },
  {
    id: 'nyc-311-complaints',
    name: 'NYC 311 Complaints (Recent)',
    category: 'nyc',
    endpoint: 'https://data.cityofnewyork.us/resource/erm2-nwe9.json?$order=created_date%20DESC&$limit=50',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Latest 311 complaints — noise, potholes, rats, everything wrong with the city',
  },
  {
    id: 'nyc-restaurant-inspections',
    name: 'NYC Restaurant Inspections',
    category: 'nyc',
    endpoint: 'https://data.cityofnewyork.us/resource/43nn-pn8j.json?$order=inspection_date%20DESC&$limit=50',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Latest restaurant health inspection results — who got the rats',
  },
  {
    id: 'nyc-motor-vehicle-collisions',
    name: 'NYC Motor Vehicle Collisions',
    category: 'nyc',
    endpoint: 'https://data.cityofnewyork.us/resource/h9gi-nx95.json?$order=crash_date%20DESC&$limit=50',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Recent motor vehicle crashes with location, injuries, fatalities',
  },
  {
    id: 'nyc-building-permits',
    name: 'NYC Building Permits (Recent)',
    category: 'nyc',
    endpoint: 'https://data.cityofnewyork.us/resource/ipu4-2vj7.json?$order=issued_date%20DESC&$limit=50',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Recent building permits — where NYC is building next',
  },
  {
    id: 'nyc-evictions',
    name: 'NYC Evictions',
    category: 'nyc',
    endpoint: 'https://data.cityofnewyork.us/resource/6z8x-wfk4.json?$order=executed_date%20DESC&$limit=50',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Recent eviction filings — housing crisis in real-time',
  },
  {
    id: 'nyc-shooting-incidents',
    name: 'NYC Shooting Incidents',
    category: 'nyc',
    endpoint: 'https://data.cityofnewyork.us/resource/5ucz-vwe8.json?$order=occur_date%20DESC&$limit=50',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'NYPD shooting incident data',
  },
  {
    id: 'mta-subway-status',
    name: 'MTA Subway Service Status',
    category: 'nyc',
    endpoint: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/camsys%2Fsubway-alerts.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 60_000,
    description: 'Real-time subway service alerts — delays, reroutes, suspensions',
  },
  {
    id: 'nyc-ferry-ridership',
    name: 'NYC Ferry GTFS',
    category: 'nyc',
    endpoint: 'https://nycferry.connexionz.net/rtt/public/utility/gtfsrealtime.aspx/tripupdate',
    method: 'GET',
    auth: 'none',
    refreshMs: 60_000,
    description: 'Real-time NYC ferry positions and trip updates',
  },
];

// ============================================================================
// MEMES / SOCIAL SIGNALS / CULTURE METRICS
// ============================================================================
export const MEME_API_SOURCES: ApiSource[] = [
  {
    id: 'reddit-memes-hot',
    name: 'Reddit r/memes Hot',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/memes/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Hot memes from r/memes — the internet\'s meme thermometer',
  },
  {
    id: 'reddit-dankmemes',
    name: 'Reddit r/dankmemes Hot',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/dankmemes/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Dank memes — higher volatility meme index',
  },
  {
    id: 'reddit-surrealmemes',
    name: 'Reddit r/surrealmemes',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/surrealmemes/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Surreal memes — the avant-garde indicator',
  },
  {
    id: 'reddit-shitposting',
    name: 'Reddit r/shitposting',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/shitposting/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Shitposting — degeneracy sentiment gauge',
  },
  {
    id: 'reddit-copypasta',
    name: 'Reddit r/copypasta',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/copypasta/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Copypasta — viral text mutations tracker',
  },
  {
    id: 'reddit-internetculture',
    name: 'Reddit r/internetculture',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/internetculture/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Internet culture meta-commentary',
  },
  {
    id: 'imgflip-trending',
    name: 'Imgflip Popular Memes',
    category: 'memes',
    endpoint: 'https://api.imgflip.com/get_memes',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Most popular meme templates — which formats are trending',
  },
  {
    id: 'reddit-outoftheloop',
    name: 'Reddit r/OutOfTheLoop',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/OutOfTheLoop/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'What normies are confused about — cultural diffusion tracker',
  },
  {
    id: 'reddit-subredditdrama',
    name: 'Reddit r/SubredditDrama',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/SubredditDrama/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Internet drama index — online conflict tracker',
  },
  {
    id: 'reddit-bestof',
    name: 'Reddit r/bestof',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/bestof/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Best of Reddit — signal from the noise',
  },
  {
    id: 'reddit-tifu',
    name: 'Reddit r/tifu',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/tifu/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Today I Fucked Up — human disaster index',
  },
  {
    id: 'reddit-aita',
    name: 'Reddit r/AmItheAsshole',
    category: 'memes',
    endpoint: 'https://www.reddit.com/r/AmItheAsshole/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'AITA — moral compass calibration index',
  },
];

// ============================================================================
// SPACE / WEATHER / NATURAL PHENOMENA
// ============================================================================
export const SPACE_API_SOURCES: ApiSource[] = [
  {
    id: 'iss-position',
    name: 'ISS Current Position',
    category: 'space',
    endpoint: 'http://api.open-notify.org/iss-now.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 10_000,
    description: 'International Space Station real-time lat/lng',
  },
  {
    id: 'people-in-space',
    name: 'People In Space Right Now',
    category: 'space',
    endpoint: 'http://api.open-notify.org/astros.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Current number of humans in space and who they are',
  },
  {
    id: 'nasa-apod',
    name: 'NASA Astronomy Picture of the Day',
    category: 'space',
    endpoint: 'https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY',
    method: 'GET',
    auth: 'none',
    refreshMs: 86_400_000,
    description: 'Daily astronomy photo with explanation',
  },
  {
    id: 'nasa-neo',
    name: 'NASA Near Earth Objects',
    category: 'space',
    endpoint: 'https://api.nasa.gov/neo/rest/v1/feed/today?api_key=DEMO_KEY',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Asteroids and comets approaching Earth today',
  },
  {
    id: 'space-weather-alerts',
    name: 'NOAA Space Weather Alerts',
    category: 'space',
    endpoint: 'https://services.swpc.noaa.gov/products/alerts.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Solar flares, geomagnetic storms, radiation belt alerts',
  },
  {
    id: 'solar-wind',
    name: 'Solar Wind Speed',
    category: 'space',
    endpoint: 'https://services.swpc.noaa.gov/products/summary/solar-wind-speed.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 60_000,
    description: 'Real-time solar wind speed from NOAA DSCOVR satellite',
  },
  {
    id: 'geomagnetic-kp',
    name: 'Geomagnetic Kp Index',
    category: 'space',
    endpoint: 'https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Planetary K-index — aurora probability indicator',
  },
  {
    id: 'solar-flare-xray',
    name: 'Solar X-Ray Flux',
    category: 'space',
    endpoint: 'https://services.swpc.noaa.gov/json/goes/primary/xrays-6-hour.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 60_000,
    description: 'Real-time solar X-ray flux from GOES satellite',
  },
  {
    id: 'aurora-forecast',
    name: 'Aurora Forecast',
    category: 'space',
    endpoint: 'https://services.swpc.noaa.gov/json/ovation_aurora_latest.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Northern/Southern lights probability map',
  },
];

// ============================================================================
// EARTH / WEATHER / NATURAL DISASTERS
// ============================================================================
export const EARTH_API_SOURCES: ApiSource[] = [
  {
    id: 'usgs-earthquakes-hour',
    name: 'USGS Earthquakes (Past Hour)',
    category: 'earth',
    endpoint: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson',
    method: 'GET',
    auth: 'none',
    refreshMs: 60_000,
    description: 'All earthquakes in the past hour worldwide',
  },
  {
    id: 'usgs-earthquakes-day-significant',
    name: 'USGS Significant Earthquakes (Today)',
    category: 'earth',
    endpoint: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_day.geojson',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Significant earthquakes today',
  },
  {
    id: 'noaa-weather-alerts',
    name: 'NWS Active Weather Alerts',
    category: 'earth',
    endpoint: 'https://api.weather.gov/alerts/active?status=actual&severity=Extreme,Severe',
    method: 'GET',
    auth: 'none',
    refreshMs: 120_000,
    description: 'Active severe/extreme weather alerts across the US',
  },
  {
    id: 'noaa-weather-nyc',
    name: 'NYC Weather Forecast',
    category: 'earth',
    endpoint: 'https://api.weather.gov/gridpoints/OKX/33,37/forecast',
    method: 'GET',
    auth: 'none',
    refreshMs: 1_800_000,
    description: 'NYC weather forecast from NWS',
  },
  {
    id: 'openaq-nyc',
    name: 'NYC Air Quality',
    category: 'earth',
    endpoint: 'https://api.openaq.org/v2/latest?city=New%20York&limit=10',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Real-time air quality measurements in NYC',
  },
  {
    id: 'wildfire-active',
    name: 'Active Wildfires (US)',
    category: 'earth',
    endpoint: 'https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/Active_Fires/FeatureServer/0/query?where=1%3D1&outFields=*&f=json&resultRecordCount=50&orderByFields=FireDiscoveryDateTime%20DESC',
    method: 'GET',
    auth: 'none',
    refreshMs: 900_000,
    description: 'Currently active wildfires in the US',
  },
  {
    id: 'volcano-alerts',
    name: 'USGS Volcano Alerts',
    category: 'earth',
    endpoint: 'https://volcanoes.usgs.gov/hans2/api/volcanoAlerts',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Active volcano alerts and aviation color codes',
  },
  {
    id: 'tsunami-alerts',
    name: 'Tsunami Alerts',
    category: 'earth',
    endpoint: 'https://www.tsunami.gov/events/xml/PAAQAtom.xml',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Pacific Tsunami Warning Center alerts',
  },
];

// ============================================================================
// THREAT INTELLIGENCE / CYBER FEEDS (machine-readable)
// ============================================================================
export const THREAT_INTEL_SOURCES: ApiSource[] = [
  {
    id: 'cisa-kev',
    name: 'CISA Known Exploited Vulnerabilities',
    category: 'threat-intel',
    endpoint: 'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Actively exploited CVEs that agencies must patch — the "oh shit" list',
  },
  {
    id: 'nvd-cve-recent',
    name: 'NVD Recent CVEs',
    category: 'threat-intel',
    endpoint: 'https://services.nvd.nist.gov/rest/json/cves/2.0?resultsPerPage=20',
    method: 'GET',
    auth: 'none',
    refreshMs: 1_800_000,
    description: 'Latest CVE vulnerability disclosures from NIST NVD',
  },
  {
    id: 'abuse-ch-urlhaus',
    name: 'URLhaus Malicious URLs',
    category: 'threat-intel',
    endpoint: 'https://urlhaus-api.abuse.ch/v1/urls/recent/',
    method: 'POST',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Recently reported malicious URLs — phishing/malware distribution',
  },
  {
    id: 'abuse-ch-malware-bazaar',
    name: 'MalwareBazaar Recent',
    category: 'threat-intel',
    endpoint: 'https://mb-api.abuse.ch/api/v1/',
    method: 'POST',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Recently submitted malware samples with hashes and tags',
  },
  {
    id: 'abuse-ch-feodo',
    name: 'Feodo Tracker C2 IPs',
    category: 'threat-intel',
    endpoint: 'https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Active command & control server IPs for banking trojans',
  },
  {
    id: 'abuse-ch-sslblacklist',
    name: 'SSL Blacklist',
    category: 'threat-intel',
    endpoint: 'https://sslbl.abuse.ch/blacklist/sslblacklist.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'SSL certificates used by botnet C&C servers',
  },
  {
    id: 'openphish-feed',
    name: 'OpenPhish Community Feed',
    category: 'threat-intel',
    endpoint: 'https://openphish.com/feed.txt',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Curated list of active phishing URLs',
  },
  {
    id: 'cert-transparency',
    name: 'Certificate Transparency Log',
    category: 'threat-intel',
    endpoint: 'https://crt.sh/atom?q=%25.gov',
    method: 'GET',
    auth: 'none',
    refreshMs: 1_800_000,
    description: 'New SSL certificates for .gov domains — detect impersonation',
  },
  {
    id: 'tor-exit-nodes',
    name: 'Tor Exit Nodes',
    category: 'threat-intel',
    endpoint: 'https://check.torproject.org/torbulkexitlist',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Current list of Tor exit relay IP addresses',
  },
  {
    id: 'cloudflare-radar',
    name: 'Cloudflare Radar Outages',
    category: 'threat-intel',
    endpoint: 'https://radar.cloudflare.com/api/v1/annotations/outages?limit=10&dateRange=1d',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Internet outages and traffic anomalies detected by Cloudflare',
  },
];

// ============================================================================
// GOVERNMENT / FEDERAL DATA
// ============================================================================
export const GOV_API_SOURCES: ApiSource[] = [
  {
    id: 'federal-register',
    name: 'Federal Register (Today)',
    category: 'government',
    endpoint: 'https://www.federalregister.gov/api/v1/documents.json?conditions[publication_date][is]=today&per_page=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'New federal regulations, executive orders, and notices published today',
  },
  {
    id: 'federal-register-significant',
    name: 'Significant Federal Register Docs',
    category: 'government',
    endpoint: 'https://www.federalregister.gov/api/v1/documents.json?conditions[significant]=1&per_page=10&order=newest',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Significant regulatory actions — the ones that actually matter',
  },
  {
    id: 'fda-drug-approvals',
    name: 'FDA Drug Approvals',
    category: 'government',
    endpoint: 'https://api.fda.gov/drug/drugsfda.json?sort=submissions.submission_status_date:desc&limit=20',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Recent FDA drug approval decisions',
  },
  {
    id: 'fda-recalls',
    name: 'FDA Recalls & Safety Alerts',
    category: 'government',
    endpoint: 'https://api.fda.gov/food/enforcement.json?sort=report_date:desc&limit=20',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Food and drug recalls — what\'s being pulled off shelves',
  },
  {
    id: 'fda-adverse-events',
    name: 'FDA Adverse Events',
    category: 'government',
    endpoint: 'https://api.fda.gov/drug/event.json?sort=receiptdate:desc&limit=20',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Reported drug adverse events',
  },
  {
    id: 'sec-edgar-filings',
    name: 'SEC EDGAR Recent Filings',
    category: 'government',
    endpoint: 'https://efts.sec.gov/LATEST/search-index?q=%22form-type%22:%2210-K%22&dateRange=custom&startdt=2026-03-18&enddt=2026-03-19',
    method: 'GET',
    auth: 'none',
    refreshMs: 1_800_000,
    description: 'Recent SEC filings',
  },
  {
    id: 'fcc-filings',
    name: 'FCC Recent Filings',
    category: 'government',
    endpoint: 'https://opendata.fcc.gov/resource/i5zg-p5dz.json?$order=date_received%20DESC&$limit=20',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Recent FCC filings and applications',
  },
  {
    id: 'cfpb-complaints',
    name: 'CFPB Consumer Complaints',
    category: 'government',
    endpoint: 'https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?field=all&sort=created_date_desc&size=20',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Consumer complaints about financial products — bank rage index',
  },
  {
    id: 'fred-gdp',
    name: 'FRED GDP Data',
    category: 'government',
    endpoint: 'https://api.stlouisfed.org/fred/series/observations?series_id=GDP&api_key=DEMO_KEY&file_type=json&sort_order=desc&limit=10',
    method: 'GET',
    auth: 'key',
    refreshMs: 86_400_000,
    description: 'US GDP from Federal Reserve Economic Data',
  },
  {
    id: 'treasury-rates',
    name: 'Treasury Yield Curve Rates',
    category: 'government',
    endpoint: 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/daily-treasury-rates.csv/all/today?type=daily_treasury_yield_curve&field_tdr_date_value=2026&page&_format=json',
    method: 'GET',
    auth: 'none',
    refreshMs: 3_600_000,
    description: 'Daily Treasury yield curve rates — THE risk-free rate',
  },
  {
    id: 'patent-recent',
    name: 'USPTO Recent Patents',
    category: 'government',
    endpoint: 'https://developer.uspto.gov/api/v1/patent/applications?rows=20&start=0&largeTextSearchFlag=N&sort=app_filing_date+desc',
    method: 'GET',
    auth: 'none',
    refreshMs: 86_400_000,
    description: 'Recent patent applications — who\'s innovating what',
  },
];

// ============================================================================
// INFRASTRUCTURE / GRID / TRANSPORT
// ============================================================================
export const INFRA_API_SOURCES: ApiSource[] = [
  {
    id: 'faa-airport-delays',
    name: 'FAA Airport Delays',
    category: 'infrastructure',
    endpoint: 'https://nasstatus.faa.gov/api/airport-status-information',
    method: 'GET',
    auth: 'none',
    refreshMs: 120_000,
    description: 'Real-time US airport delay and closure status',
  },
  {
    id: 'ais-ship-density',
    name: 'AIS Ship Tracking',
    category: 'infrastructure',
    endpoint: 'https://aisstream.io/api/v1/ships',
    method: 'GET',
    auth: 'key',
    refreshMs: 60_000,
    description: 'Real-time ship positions via AIS — global maritime traffic',
  },
  {
    id: 'opensky-flights',
    name: 'OpenSky Flight Tracker',
    category: 'infrastructure',
    endpoint: 'https://opensky-network.org/api/states/all?lamin=40.4&lomin=-74.3&lamax=40.9&lomax=-73.7',
    method: 'GET',
    auth: 'none',
    refreshMs: 30_000,
    description: 'All aircraft currently over NYC metro area',
  },
  {
    id: 'ercot-grid',
    name: 'ERCOT Grid Conditions',
    category: 'infrastructure',
    endpoint: 'https://www.ercot.com/api/1/services/read/dashboards/daily-prc.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Texas power grid status — is Texas about to freeze again?',
  },
  {
    id: 'caiso-renewables',
    name: 'CAISO Renewables Watch',
    category: 'infrastructure',
    endpoint: 'https://www.caiso.com/outlook/SP/renewables.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'California ISO real-time renewable generation mix',
  },
  {
    id: 'downdetector-scrape',
    name: 'Major Service Outages',
    category: 'infrastructure',
    endpoint: 'https://downdetector.com/api/v2/companies/trending',
    method: 'GET',
    auth: 'none',
    refreshMs: 120_000,
    description: 'Trending outage reports — what\'s broken right now',
  },
  {
    id: 'submarine-cables',
    name: 'Submarine Cable Map',
    category: 'infrastructure',
    endpoint: 'https://www.submarinecablemap.com/api/v3/cable/cable-geo.json',
    method: 'GET',
    auth: 'none',
    refreshMs: 86_400_000,
    description: 'Global submarine internet cable infrastructure',
  },
];

// ============================================================================
// SOCIAL PLATFORM SIGNALS (public JSON endpoints)
// ============================================================================
export const SOCIAL_API_SOURCES: ApiSource[] = [
  {
    id: 'reddit-all-hot',
    name: 'Reddit r/all Hot',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/all/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 120_000,
    description: 'Hottest posts across all of Reddit right now',
  },
  {
    id: 'reddit-popular',
    name: 'Reddit Popular',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/popular.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 120_000,
    description: 'Most popular Reddit posts',
  },
  {
    id: 'reddit-technology',
    name: 'Reddit r/technology',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/technology/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Tech discourse on Reddit',
  },
  {
    id: 'reddit-worldnews',
    name: 'Reddit r/worldnews',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/worldnews/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Breaking world news from Reddit',
  },
  {
    id: 'reddit-politics',
    name: 'Reddit r/politics',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/politics/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'US political discourse',
  },
  {
    id: 'reddit-wallstreetbets',
    name: 'Reddit r/wallstreetbets',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/wallstreetbets/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 120_000,
    description: 'Degen trading and financial nihilism',
  },
  {
    id: 'reddit-cryptocurrency',
    name: 'Reddit r/cryptocurrency',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/CryptoCurrency/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Crypto community sentiment',
  },
  {
    id: 'reddit-collapse',
    name: 'Reddit r/collapse',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/collapse/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Civilizational collapse tracking — doomer sentiment index',
  },
  {
    id: 'reddit-upliftingnews',
    name: 'Reddit r/UpliftingNews',
    category: 'social',
    endpoint: 'https://www.reddit.com/r/UpliftingNews/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Good news — hopium supply index',
  },
  {
    id: 'steam-top-games',
    name: 'Steam Most Played',
    category: 'social',
    endpoint: 'https://api.steampowered.com/ISteamChartsService/GetMostPlayedGames/v1/',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Currently most played games on Steam',
  },
  {
    id: 'steam-news',
    name: 'Steam News Hub',
    category: 'social',
    endpoint: 'https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/?appid=0&count=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Latest gaming news from Steam',
  },
];

// ============================================================================
// CRYPTO / DEFI APIs (beyond RSS)
// ============================================================================
export const CRYPTO_API_SOURCES: ApiSource[] = [
  {
    id: 'bitcoin-mempool',
    name: 'Bitcoin Mempool Stats',
    category: 'crypto-data',
    endpoint: 'https://mempool.space/api/mempool',
    method: 'GET',
    auth: 'none',
    refreshMs: 30_000,
    description: 'Bitcoin mempool congestion — unconfirmed tx count and fees',
  },
  {
    id: 'bitcoin-hashrate',
    name: 'Bitcoin Hashrate',
    category: 'crypto-data',
    endpoint: 'https://mempool.space/api/v1/mining/hashrate/1w',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Bitcoin network hashrate — mining power gauge',
  },
  {
    id: 'bitcoin-blocks',
    name: 'Bitcoin Latest Blocks',
    category: 'crypto-data',
    endpoint: 'https://mempool.space/api/v1/blocks',
    method: 'GET',
    auth: 'none',
    refreshMs: 60_000,
    description: 'Latest Bitcoin blocks with size, fees, tx count',
  },
  {
    id: 'eth-gas-price',
    name: 'Ethereum Gas Price',
    category: 'crypto-data',
    endpoint: 'https://api.etherscan.io/api?module=gastracker&action=gasoracle',
    method: 'GET',
    auth: 'none',
    refreshMs: 15_000,
    description: 'Real-time Ethereum gas prices in Gwei',
  },
  {
    id: 'defi-llama-tvl',
    name: 'DeFi Total Value Locked',
    category: 'crypto-data',
    endpoint: 'https://api.llama.fi/protocols',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'TVL across all DeFi protocols — where money is parked',
  },
  {
    id: 'defi-llama-chains',
    name: 'DeFi TVL by Chain',
    category: 'crypto-data',
    endpoint: 'https://api.llama.fi/v2/chains',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'TVL breakdown by blockchain — which chain is winning',
  },
  {
    id: 'defi-llama-stablecoins',
    name: 'Stablecoin Market',
    category: 'crypto-data',
    endpoint: 'https://stablecoins.llama.fi/stablecoins?includePrices=true',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Stablecoin market caps and pegs — are they still $1?',
  },
  {
    id: 'coingecko-global',
    name: 'Crypto Global Market Data',
    category: 'crypto-data',
    endpoint: 'https://api.coingecko.com/api/v3/global',
    method: 'GET',
    auth: 'none',
    refreshMs: 300_000,
    description: 'Total crypto market cap, volume, BTC dominance',
  },
];

// ============================================================================
// ADULT INDUSTRY / GOONING INTELLIGENCE / HORNY METRICS
// ============================================================================
export const HORNY_API_SOURCES: ApiSource[] = [
  {
    id: 'reddit-onlyfansadvice',
    name: 'Reddit r/onlyfansadvice',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/onlyfansadvice/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'OnlyFans creator discourse — the creator economy\'s spiciest corner',
  },
  {
    id: 'reddit-creatorsadvice',
    name: 'Reddit r/CreatorsAdvice',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/CreatorsAdvice/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Adult content creator meta — platform strategy and earnings',
  },
  {
    id: 'reddit-nofap',
    name: 'Reddit r/NoFap',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/NoFap/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Anti-gooning resistance index — the counter-signal',
  },
  {
    id: 'reddit-gooncaves',
    name: 'Reddit Goon Community',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/gooned/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Gooning culture signal — internet brainrot thermometer',
  },
  {
    id: 'reddit-sex-workers',
    name: 'Reddit r/SexWorkersOnly',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/SexWorkersOnly/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Sex work industry sentiment — labor conditions and platform changes',
  },
  {
    id: 'reddit-relationships',
    name: 'Reddit r/relationships',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/relationships/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Relationship discourse — the human connection index',
  },
  {
    id: 'reddit-deadbedrooms',
    name: 'Reddit r/DeadBedrooms',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/DeadBedrooms/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Sexual dissatisfaction index — inverse of gooning metrics',
  },
  {
    id: 'reddit-tinder',
    name: 'Reddit r/Tinder',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/Tinder/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Dating app desperation index',
  },
  {
    id: 'reddit-pornfree',
    name: 'Reddit r/pornfree',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/pornfree/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Porn recovery community — the rebound signal',
  },
  {
    id: 'reddit-sexeconomy',
    name: 'Reddit r/DigitalSexEconomy',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/DigitalSexEconomy/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'Digital sex economy discussion — monetization of desire',
  },
  {
    id: 'pornhub-insights',
    name: 'Pornhub Insights (Scrape)',
    category: 'horny',
    endpoint: 'https://www.pornhub.com/insights',
    method: 'GET',
    auth: 'none',
    refreshMs: 86_400_000,
    parser: 'firecrawl-scrape',
    description: 'Pornhub traffic analytics, search trends, event impacts — WordPress blog with data viz',
  },
  {
    id: 'ofstats-top-creators',
    name: 'OnlyFans Top Creators & Stats',
    category: 'horny',
    endpoint: 'https://ofstats.net/',
    method: 'GET',
    auth: 'none',
    refreshMs: 86_400_000,
    parser: 'firecrawl-scrape',
    description: 'OnlyFans creator rankings, estimated earnings, platform revenue ($7.2B+), 4.6M+ creators',
  },
  {
    id: 'onlyfansstats-rankings',
    name: 'OnlyFans Creator Rankings',
    category: 'horny',
    endpoint: 'https://onlyfansstats.com/',
    method: 'GET',
    auth: 'none',
    refreshMs: 86_400_000,
    parser: 'firecrawl-scrape',
    description: 'Real-time OnlyFans creator rankings by followers, likes, engagement',
  },
  {
    id: 'reddit-nsfw-economy',
    name: 'Reddit r/NSFWeconomy',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/NSFWeconomy/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'NSFW creator economy discourse — business side of adult content',
  },
  {
    id: 'reddit-onlyfans-101',
    name: 'Reddit r/OnlyFans101',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/OnlyFans101/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'OnlyFans promotion subreddit — creator market activity',
  },
  {
    id: 'reddit-realgirls',
    name: 'Reddit r/RealGirls',
    category: 'horny',
    endpoint: 'https://www.reddit.com/r/RealGirls/hot.json?limit=25',
    method: 'GET',
    auth: 'none',
    refreshMs: 600_000,
    description: 'NSFW engagement metrics — baseline horny internet activity',
  },
];

// ============================================================================
// CURSED & DERANGED CUSTOM INDICES (computed from multiple sources)
// ============================================================================
// These are meta-indices computed by combining signals from multiple feeds.
// Each index has a formula for computing its value from raw feed data.
export interface CursedIndex {
  id: string;
  name: string;
  description: string;
  inputs: string[]; // IDs of data sources used to compute
  formula: string; // human-readable formula description
}

export const CURSED_INDICES: CursedIndex[] = [
  {
    id: 'degen-index',
    name: 'DEGEN INDEX',
    description: 'How degenerate is the internet right now? Higher = more unhinged.',
    inputs: [
      'reddit-wallstreetbets', 'reddit-shitposting', 'reddit-cryptocurrency',
      'bitcoin-mempool', 'eth-gas-price', 'coingecko-global',
    ],
    formula: '(WSB_engagement * 0.3) + (shitpost_velocity * 0.2) + (crypto_fear_greed * 0.2) + (gas_price_percentile * 0.15) + (mempool_congestion * 0.15)',
  },
  {
    id: 'doomer-index',
    name: 'DOOMER INDEX',
    description: 'Civilizational collapse sentiment. Higher = more people think we\'re cooked.',
    inputs: [
      'reddit-collapse', 'noaa-weather-alerts', 'usgs-earthquakes-hour',
      'cisa-kev', 'wildfire-active', 'nyc-shooting-incidents',
    ],
    formula: '(collapse_engagement * 0.25) + (severe_weather_count * 0.2) + (earthquake_mag_sum * 0.15) + (active_cves * 0.15) + (wildfire_count * 0.15) + (shooting_rate * 0.1)',
  },
  {
    id: 'hopium-index',
    name: 'HOPIUM INDEX',
    description: 'How high on hopium is the internet? Counter-signal to doomer index.',
    inputs: [
      'reddit-upliftingnews', 'reddit-bestof', 'nasa-apod',
      'people-in-space', 'steam-top-games',
    ],
    formula: '(uplifting_engagement * 0.3) + (bestof_quality * 0.2) + (space_humans * 0.2) + (gaming_concurrent * 0.15) + (nasa_amazingness * 0.15)',
  },
  {
    id: 'nyc-pulse',
    name: 'NYC PULSE',
    description: 'How alive is New York City right now? Composite activity score.',
    inputs: [
      'citibike-stations', 'nyc-traffic-speed', 'mta-subway-status',
      'nyc-311-complaints', 'opensky-flights',
    ],
    formula: '(bikes_in_use_pct * 0.25) + (avg_traffic_speed_inv * 0.2) + (subway_alerts_inv * 0.2) + (311_rate * 0.15) + (flights_overhead * 0.2)',
  },
  {
    id: 'midtown-temp',
    name: 'MIDTOWN TEMPERATURE',
    description: 'Foot traffic proxy for Midtown Manhattan. Higher = more bodies on the ground.',
    inputs: [
      'citibike-stations', 'nyc-traffic-speed', 'mta-subway-status',
      'nyc-311-complaints',
    ],
    formula: 'Midtown Citi Bike dock usage + Midtown traffic sensor speed (inverse) + subway delays affecting 1/2/3/N/Q/R/W/B/D/F/M + 311 complaints in 10001-10036 zip codes',
  },
  {
    id: 'internet-rage',
    name: 'INTERNET RAGE INDEX',
    description: 'How angry is the internet? Derived from drama and conflict signals.',
    inputs: [
      'reddit-subredditdrama', 'reddit-aita', 'reddit-politics',
      'nyc-311-complaints',
    ],
    formula: '(drama_engagement * 0.3) + (aita_controversy_score * 0.25) + (political_comment_velocity * 0.25) + (noise_complaints * 0.2)',
  },
  {
    id: 'cosmic-vibes',
    name: 'COSMIC VIBES',
    description: 'Is the universe chill or nah? Space weather + aurora + solar activity.',
    inputs: [
      'solar-wind', 'geomagnetic-kp', 'solar-flare-xray',
      'aurora-forecast', 'people-in-space',
    ],
    formula: '(solar_wind_speed * 0.2) + (kp_index * 0.25) + (xray_flux * 0.2) + (aurora_probability * 0.2) + (humans_in_space * 0.15)',
  },
  {
    id: 'meme-velocity',
    name: 'MEME VELOCITY',
    description: 'Speed of meme propagation. How fast is culture mutating?',
    inputs: [
      'reddit-memes-hot', 'reddit-dankmemes', 'imgflip-trending',
      'reddit-copypasta', 'reddit-outoftheloop',
    ],
    formula: '(meme_post_rate * 0.25) + (dankmeme_upvote_velocity * 0.25) + (new_templates * 0.2) + (copypasta_length_avg * 0.15) + (ootl_question_rate * 0.15)',
  },
  {
    id: 'grid-stress',
    name: 'GRID STRESS INDEX',
    description: 'How stressed is critical infrastructure? Power + internet + transport.',
    inputs: [
      'ercot-grid', 'caiso-renewables', 'faa-airport-delays',
      'downdetector-scrape', 'cloudflare-radar',
    ],
    formula: '(ercot_reserve_margin_inv * 0.25) + (renewable_intermittency * 0.15) + (airport_delay_count * 0.2) + (outage_reports * 0.2) + (internet_anomalies * 0.2)',
  },
  {
    id: 'regulatory-heat',
    name: 'REGULATORY HEAT MAP',
    description: 'How hard is the government coming down? Enforcement + regulations + complaints.',
    inputs: [
      'federal-register', 'fda-recalls', 'cfpb-complaints',
      'cisa-kev', 'fcc-filings',
    ],
    formula: '(new_regulations * 0.25) + (recall_count * 0.2) + (complaint_rate * 0.2) + (kev_additions * 0.15) + (fcc_actions * 0.2)',
  },
  {
    id: 'gooner-index',
    name: 'GOONER INDEX',
    description: 'How horny is the internet? Derived from adult content signals vs abstinence communities.',
    inputs: [
      'reddit-gooncaves', 'reddit-nofap', 'reddit-onlyfansadvice',
      'reddit-deadbedrooms', 'reddit-tinder',
    ],
    formula: '(gooning_engagement * 0.3) - (nofap_engagement * 0.2) + (onlyfans_creator_sentiment * 0.2) + (dead_bedrooms_despair * 0.15) + (tinder_desperation * 0.15)',
  },
  {
    id: 'touch-grass-index',
    name: 'TOUCH GRASS INDEX',
    description: 'Inverse brain rot indicator. Are people going outside or terminally online?',
    inputs: [
      'citibike-stations', 'reddit-all-hot', 'steam-top-games',
      'reddit-gooncaves', 'reddit-shitposting',
    ],
    formula: '(bikes_in_use * 0.3) - (reddit_engagement * 0.2) - (gaming_concurrent * 0.2) - (gooning_posts * 0.15) - (shitpost_rate * 0.15)',
  },
  {
    id: 'so-cooked',
    name: 'SO COOKED / SO BACK',
    description: 'Binary vibes check. Are we cooked or are we so back?',
    inputs: [
      'doomer-index', 'hopium-index', 'degen-index',
      'coingecko-global', 'reddit-all-hot',
    ],
    formula: 'if (doomer > hopium * 1.5) return "SO COOKED"; if (hopium > doomer * 1.5) return "SO BACK"; return "ITS GIVING NEUTRAL";',
  },
];

// ============================================================================
// COMBINE ALL API SOURCES
// ============================================================================
export const ALL_API_SOURCES: ApiSource[] = [
  ...NYC_API_SOURCES,
  ...MEME_API_SOURCES,
  ...SPACE_API_SOURCES,
  ...EARTH_API_SOURCES,
  ...THREAT_INTEL_SOURCES,
  ...GOV_API_SOURCES,
  ...INFRA_API_SOURCES,
  ...SOCIAL_API_SOURCES,
  ...CRYPTO_API_SOURCES,
  ...HORNY_API_SOURCES,
];

export const API_SOURCE_COUNTS = {
  nyc: NYC_API_SOURCES.length,
  memes: MEME_API_SOURCES.length,
  space: SPACE_API_SOURCES.length,
  earth: EARTH_API_SOURCES.length,
  threatIntel: THREAT_INTEL_SOURCES.length,
  government: GOV_API_SOURCES.length,
  infrastructure: INFRA_API_SOURCES.length,
  social: SOCIAL_API_SOURCES.length,
  cryptoData: CRYPTO_API_SOURCES.length,
  horny: HORNY_API_SOURCES.length,
  cursedIndices: CURSED_INDICES.length,
  total: 0,
};
API_SOURCE_COUNTS.total = ALL_API_SOURCES.length;
